stages:
  - build
  - test
  - deploy

variables:
  # ඔයාට env vars අවශ්‍ය නම්
  # EXAMPLE_VAR: "value"

build_job:
  stage: build
  image: python:3.11   # ඔයාට අනුව image එක වෙනස් කරන්න
  script:
    - pip install -r requirements.txt
    - python setup.py build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test_job:
  stage: test
  image: python:3.11
  script:
    - pip install -r requirements.txt
    - pytest tests/
  needs:
    - build_job

deploy_job:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying artifacts..."
    - apk add --no-cache openssh-client rsync
    - rsync -avz build/ user@your.server:/path/to/deploy/
  environment:
    name: production
    url: https://your.production.url
  when: manual
  only:
    - main
