stages:
  - install
  - test
  - build
  - deploy

variables:
  NODE_ENV: development

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:20
  script:
    - npm ci

test_app:
  stage: test
  image: node:20
  script:
    - npm run test -- --watchAll=false

build_app:
  stage: build
  image: node:20
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week

deploy_app:
  stage: deploy
  image: node:20
  script:
    - echo "Deploying React App..."
    # - rsync or scp or Firebase or Netlify commands
  only:
    - main
  when: manual
